spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zensar
    username: root
    password: root
  jpa:
   hibernate:
    ddl-auto: update
  application:
    name: coupon-service
  config:
    import:
    - optional:configserver:http://localhost:8888/
  zipkin:
       base-url: http://localhost:9411/   

server:
  port: 8084
  
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    
    service-url:
     defaultZone: http://localhost:8761/eureka
     
  instance:
    prefer-ip-address: true
    
      
management:
  endpoints:
    web:
      exposure:
        include:
        - "*" 

    
  
  

      

    

  

    
 