
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zensar
    username: root
    password: root
  jpa:
   hibernate:
    ddl-auto: update
    
   database-platform: org.hibernate.dialect.MySQL8Dialect
  application:
    name: product-service
   
  config:
     import: 
      - optional:configserver:http://localhost:8888/     

  
eureka:
  client:
    register-with-eureka: true
 
    fetch-registry: true
    service-url:
      defualtZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
  
server:
  port: 8089      



      
      
    
      
      
    